---
abstract: "Bandana - run PSGI application\n"
author:
  - backslash001
build_requires:
  CPAN::Meta::YAML: '0.018'
  Parse::CPAN::Meta: '2.15001'
  Test::Spec: '0.54'
configure_requires:
  CPAN::Meta: '2.15001'
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bandana
recommends:
  ExtUtils::Install: '2.2'
  ExtUtils::Manifest: '1.73'
requires:
  Data::Dumper: '0'
  Devel::Cover: '1.37'
resources:
  MailingList: mailto:telegin.vlad132@gmail.com
  license: http://dev.perl.org/licenses/
  repository: https://github.com/100backslash001/Bandana
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
